//ChuSchema v2.0, Pecacheu 2025. GNU GPL v3

import { AnyMap } from 'raiutils';

/** An error generated by `errAt` */
class SubError extends Error {}

/** Create pretty nested errors by calling this at multiple try/catch layers
@param isList Contain this segment in *[brackets]* */
function errAt(key: string | number, err: any, isList?: boolean) {
	let s=err instanceof SubError, es: string = (err as Error).message||err.toString();
	key=(isList?`[${key}]`:key)+(s ? es.startsWith('[')?'':'.' : ': ');
	if(s) (err as Error).message=key+es;
	//@ts-expect-error
	else err = new SubError(key+es, err instanceof Error?{cause:err}:null);
	return err as SubError;
}

type Type = 'str'|'int'|'float'|'bool'|'list'|'dict'|'obj';
export type Schema = {[key: string]: Entry | Entry[]}

export interface Options {
	/** Ignore schema 'req' flag */
	iReq?: boolean;

	_r?: any; //Root
	_p?: any; //Parent
	_k?: string | number; //Key
	//_n?: string; TODO Path
}

export interface HookInfo {
	/** Current key being tested. Null if at root */
	k?: string | number;
	/** Current value being tested. Null if key not found */
	v?: any;
	/** Root object given to checkSchema */
	r: any;
	//TODO Dot-separated path to key, usable with `utils.getProp`
	//p: any;
}

/** Conditional value for Schema parameter
@param par Parent object/array we're inside
@param info Extra info for advanced hooks */
export type Hook<T> = (par: any, info: HookInfo) => T;

interface GenericEntry {
	/** Required key; defaults to `true` */
	req?: boolean | Hook<boolean>;
	/** Conditionally reject this key */
	rej?: boolean | Hook<boolean>;
}
interface SizedEntry {
	/** Minimum length

	For *list* type, it defaults to `1`, otherwise `0`
	*/
	min?: number;
	/** Maximum length */
	max?: number;
	/** Exact length */
	len?: number;
}
interface NumEntry {
	/** Minimum value */
	min?: number;
	/** Maximum value */
	max?: number;
	/** Exact value */
	val?: number;
}
type ParentEntry = {
	/** Child type */
	c?: Type | Entry | Entry[];
}|{
	/** Child schema format */
	f?: Schema | Schema[];
}
export type Entry = GenericEntry & (
(SizedEntry & ({
	/** String */
	t: 'str';
	/** Regex format */
	f?: string | RegExp;
}|(ParentEntry & {
	/** Array */
	t: 'list';
})))|(ParentEntry & {
	/** Dictionary Object */
	t: 'dict';
	/** Child key format */
	k?: string | RegExp;
	/** Allow empty dict */
	z?: boolean;
})|(NumEntry & ({
	/** Integer */
	t: 'int';
}|{
	/** Float */
	t: 'float';
}))|{
	/** Boolean */
	t: 'bool';
	/** Exact value */
	val?: boolean;
}|{
	/** Specialized Object */
	t: 'obj';
	/** Class */
	c: NewableFunction;
})

function isDictOrArr(d: any) {return typeof d==='object' && d!==null}
function isDict(d: any) {return isDictOrArr(d) && !Array.isArray(d)}
function oobStr(s: SizedEntry) {return ` out-of-bounds (${s.min==null?'*':s.min}-${s.max==null?'*':s.max})`}
function dictFmt(s: any) {
	if(typeof s.c==='string') s.c={t:s.c};
	let dt=isDictOrArr(s.f)?2:isDictOrArr(s.c)?1:0;
	if(!dt) throw "Schema lacks format or childType";
	if(dt===2 && s.c) throw "Cannot require both format and childType";
	return dt===2;
}
function tryAny<T>(a: T | T[], fn: (v: T) => void) {
	if(Array.isArray(a)) {
		let el: any[]=[];
		for(const s of a) try {fn(s); return} catch(e) {el.push(e)}
		throw "(Failed all cases) "+el.map(e => e.message||e).join(', ');
	} else fn(a);
}
function runHook<T>(t: T | Hook<T>, k: any, v: any, o: Options): T {
	if(typeof t==='function') return (t as Hook<T>)(o._p, {k, v, r:o._r});
	return t;
}

/** Check value against a schema entry
@param val Item to validate
@param ent Schema Entry(s) to use */
function checkType(val: any, ent: Entry | Entry[], opt?: Options) {
	//Cache root & parent
	let l,k,d,n,dt,sr;
	if(!opt) opt={};
	if(!('_r' in opt)) opt._r=val, sr=1;
	if(!('_p' in opt)) opt._p=val;

	try {tryAny(ent, s => {try {
		if(runHook(s.rej, opt._k, val, opt)) throw "Disallowed key";
		switch(s.t) {
		case 'str':
			if(typeof val!=='string') throw -1;
			l=val.length;
			if(l<s.min! || l>s.max!) throw "Str len "+l+oobStr(s);
			if(s.len!=null && l!==s.len) throw "Str len must be "+s.len;
			if(typeof s.f==='string') s.f=new RegExp(`^(?:${s.f})$`);
			if(s.f && !s.f.test(val)) throw `Str '${val}' does not match format ${s.f}`;
		break; case 'int': case 'float':
			if(typeof val!=='number' || !(s.t==='int'?Number.isSafeInteger(val):Number.isFinite(val))) throw -1;
			if(s.val!=null && val!==s.val) throw "Num != "+s.val;
			if(val<s.min! || val>s.max!) throw "Num "+val+oobStr(s);
		break; case 'bool':
			if(typeof val!=='boolean') throw -1;
			if(s.val!=null && val!==s.val) throw "Bool != "+s.val;
		break; case 'list':
			if(!Array.isArray(val)) throw -1;
			l=val.length; if(!l && s.min!==0) throw "Empty list";
			if(s.len!=null && l!==s.len) throw "Array size must be "+s.len;
			if(l<s.min! || l>s.max!) throw "Array size "+l+oobStr(s);
			n=0, dt=dictFmt(s), d={...opt, _p:val};
			for(; n<l; ++n) try {
				d._k=n;
				//@ts-expect-error
				dt?checkSchema(val[n], s.f, d):checkType(val[n], s.c, d);
			} catch(e) {throw errAt(n,e,true)}
		break; case 'dict':
			if(!isDict(val)) throw -1;
			k=Object.keys(val);
			if(!k.length && !s.z) throw "Empty dict";
			if(typeof s.k==='string') s.k=new RegExp(`^(?:${s.k})$`);
			dt=dictFmt(s), d={...opt, _p:val};
			for(n of k) try {
				if(n.startsWith('$')) throw "Key cannot start with $";
				if(s.k && !s.k.test(n)) throw `Key '${n}' does not match format ${s.k}`;
				d._k=n;
				//@ts-expect-error
				dt?checkSchema(val[n], s.f, d):checkType(val[n], s.c, d);
			} catch(e) {throw errAt(n,e,true)}
		break; case 'obj':
			if(typeof s.c !== 'function') throw "Obj schema requires class";
			if(!(val instanceof s.c)) throw `Obj must be of type ${s.c.name}`;
		break; default:
			throw `Unknown type ${(s as any).t} in schema`;
		}
	} catch(e) {
		if(e === -1) throw "Must be of type "+s.t;
		throw e;
	}})} finally {if(sr) delete opt._r, delete opt._p}
}

/** Check data against a schema
@param data Object to validate
@param schema ChuSchema(s) to use */
function checkSchema(data: AnyMap, schema: Schema | Schema[], opt?: Options) {
	if(!isDict(data)) throw "Data must be dict";
	if(!isDictOrArr(schema)) throw "Schema must be dict|list[dict]";

	//Cache root & parent
	let k,s,sr;
	if(!opt) opt={};
	if(!('_r' in opt)) opt._r=data, sr=1;
	opt._p=data;

	try {tryAny(schema, sch => {
		for(k in data) try {
			s=sch[k];
			if(!s) throw "Not in schema";
			if(k.startsWith('$')) throw "Key cannot start with $";
			opt._k=k;
			checkType(data[k], s, opt);
		} catch(e) {throw errAt(k,e)}
		if(opt.iReq) return;
		//Check missing
		for(k in sch) if(!(k in data)) {
			s=sch[k]!;
			if(Array.isArray(s)) s=s[0]!;
			if(s.req == null || runHook(s.req, k, null, opt)) throw k+": Required";
		}
	})} finally {
		if(sr) delete opt._r;
		delete opt._p, delete opt._k;
	}
}

function isNumArr(a: any[]) {
	for(let v of a) if(typeof v!=='number') return;
	return 1;
}

/** Custom JSON stringify implementation w/ better line-breaks */
function prettyJSON(val: any, _d=0) {
	let t=typeof val;
	if(t==='number' || t==='string' || t==='boolean') return JSON.stringify(val);
	else if(Array.isArray(val)) {
		if(isNumArr(val)) return JSON.stringify(val);
		let s='[',d1=_d+1,i=0,l=val.length;
		for(; i<l; ++i) s += (i?',\n':'\n')+('\t'.repeat(d1))+prettyJSON(val[i],d1);
		return s+'\n'+'\t'.repeat(_d)+']';
	} else if(t==='object') {
		let k,s='{',ln: any=!_d,f,d1=_d+1;
		for(k in val) {
			if(Array.isArray(val[k]) && !isNumArr(val[k])) ln=1;
			s += (ln?f?',\n':'\n':f?', ':'')+'\t'.repeat(ln?d1:0)+JSON.stringify(k)+":"+prettyJSON(val[k],d1);
			f=1,ln=0;
		}
		if(!_d) s+='\n';
		return s+'}';
	} else throw "Unknown type "+t;
}

export default {SubError, errAt, checkSchema, checkType, prettyJSON}